export enum DrawModule_t {
	W3DDEBRISDRAW = "W3DDebrisDraw",
	W3DDEFAULT = "W3DDefaultDraw",
	W3DDependencyModelDraw = "W3DDependencyModelDraw",
	W3DModelDraw = "W3DModelDraw",
	W3DOverlordTankDraw = "W3DOverlordTankDraw",
	W3DOverlordAircraftDraw = "W3DOverlordAircraftDraw",
	W3DOverlordTruckDraw = "W3DOverlordTruckDraw",
	W3DLaserDraw = "W3DLaserDraw",
	W3DPoliceCardDraw = "W3DPoliceCardDraw",
	W3DTreedraw = "W3DTreedraw",
	W3DPropDraw = "W3DPropDraw",
	W3DProjectileStreamDraw = "W3DProjectileStreamDraw",
	W3DDropedraw = "W3DDropedraw",
	W3DScienceModelDraw = "W3DScienceModelDraw",
	W3DSupplyDraw = "W3DSupplyDraw",
	W3DTankDraw = "W3DTankDraw",
	W3DTankTruckDraw = "W3DTankTruckDraw",
	W3DTracerDraw = "W3DTracerDraw",
	W3DTruckDraw = "W3DTruckDraw"
}