export enum BuildCompletion_t {
	NONE = 'NONE',
	INVALID = 'INVALID',
	APPEARS_AT_RALLY_POINT = 'APPEARS_AT_RALLY_POINT',
	PLACED_BY_PLAYER = 'PLACED_BY_PLAYER'
}

export enum RadarPriority_t {
	NONE = 'NONE',
	NOT_ON_RADAR = 'NOT_ON_RADAR',
	STRUCTURE = 'STRUCTURE',
	UNIT = 'UNIT',
	BOMB = 'BOMB',
	NUM_PRIORITIES = 'NUM_PRIORITIES',
	LOCAL_UNIT_ONLY = 'LOCAL_UNIT_ONLY'
}

export enum MaxSimultaneousLinkKey_t {
	INT = 'INT',
	DETERMINED_BY_SUPERWEAPON_RESTRICTION = 'DeterminedBySuperweaponRestriction'
}

export enum EditorSorting_t {
	NONE = 'NONE',
	STRUCTURE = 'STRUCTURE',
	VEHICLE = 'VEHICLE',
	INFANTRY = 'INFANTRY',
	SHRUBBERY = 'SHRUBBERY',
	MISC_MAN_MADE = 'MISC_MAN_MADE',
	MISC_NATURAL = 'MISC_NATURAL',
	DEBRIS = 'DEBRIS',
	SYSTEM = 'SYSTEM',
	AUDIO = 'AUDIO',
	TEST = 'TEST',
	FOR_REVIEW = 'FOR_REVIEW',
	ROAD = 'ROAD',
	WAYPOINT = 'WAYPOINT'
}

export enum LOD_t {
	LOW = 'LOW',
	MEDIUM = 'MEDIUM',
	HIGH = 'HIGH'
}

export enum AnimationMode_t {
	MANUAL = 'MANUAL',
	LOOP = 'LOOP',
	PING_PONG = 'PING_PONG'
}

export enum ConditionStateFlags_t {
	NONE = 'NONE',
	DISABLE_ANIMATION = 'DISABLE_ANIMATION'
}

export enum WeaponSlot_t {
	PRIMARY = 'PRIMARY',
	SECONDARY = 'SECONDARY',
	TERTIARY = 'TERTIARY'
}

export enum Locomotor_types_t {
	SET_NORMAL = 'SET_NORMAL',
	SET_PANIC = 'SET_PANIC',
	SET_NORMAL_UPGRADED = 'SET_NORMAL_UPGRADED',
	SET_SUPERSONIC = 'SET_SUPERSONIC',
	SET_SLUGGISH = 'SET_SLUGGISH',
	SET_TAXIING = 'SET_TAXIING',
	SET_FREEFALL = 'SET_FREEFALL',
	SET_WANDER = 'SET_WANDER'
}
