export enum BuildCompletion_t {
	NONE = 'NONE',
	INVALID = 'INVALID',
	APPEARS_AT_RALLY_POINT = 'APPEARS_AT_RALLY_POINT',
	PLACED_BY_PLAYER = 'PLACED_BY_PLAYER'
}

export enum Shadow_t {
	NONE = 'NONE',
	SHADOW_VOLUME = 'SHADOW_VOLUME',
	SHADOW_DECAL = 'SHADOW_DECAL',
	SHADOW_PROJECTION = 'SHADOW_PROJECTION',
	SHADOW_DYNAMIC_PROJECTION = 'SHADOW_DYNAMIC_PROJECTION',
	SHADOW_DIRECTIONAL_PROJECTION = 'SHADOW_DIRECTIONAL_PROJECTION',
	SHADOW_ALPHA_DECAL = 'SHADOW_ALPHA_DECAL',
	SHADOW_ADDITIVE_DECAL = 'SHADOW_ADDITIVE_DECAL'
}

export enum RadarPriority_t {
	NONE = 'NONE',
	NOT_ON_RADAR = 'NOT_ON_RADAR',
	STRUCTURE = 'STRUCTURE',
	UNIT = 'UNIT',
	BOMB = 'BOMB',
	NUM_PRIORITIES = 'NUM_PRIORITIES',
	LOCAL_UNIT_ONLY = 'LOCAL_UNIT_ONLY'
}

export enum Side_t {
	CIVILIAN = 'Civilian',
	OBSERVER = 'Observer',
	BOSS = 'Boss',
	AMERICA = 'America',
	GLA = 'GLA',
	CHINA = 'China',
	AMERICA_SUPERWEAPON_GENERAL = 'AmericaSuperweaponGeneral',
	AMERICA_LASER_GENERAL = 'AmericaLaserGeneral',
	AMERICA_AIRFORCE_GENERAL = 'AmericaAirforceGeneral',
	GLA_TOXIN_GENERAL = 'GlaToxinGeneral',
	GLA_DEMOLITION_GENERAL = 'GlaDemolitionGeneral',
	GLA_STEALTH_GENERAL = 'GlaStealthGeneral',
	CHINA_TANK_GENERAL = 'ChinaTankGeneral',
	CHINA_NUKE_GENERAL = 'ChinaNukeGeneral',
	CHINA_INFANTRY_GENERAL = 'ChinaInfantryGeneral',
}

export enum MaxSimultaneousLinkKey_t {
	INT = 'INT',
	DETERMINED_BY_SUPERWEAPON_RESTRICTION = 'DeterminedBySuperweaponRestriction'
}

export enum DeathType_t {
	ALL = 'ALL',
	NORMAL = 'NORMAL',
	CRUSHED = 'CRUSHED',
	BURNED = 'BURNED',
	EXPLODED = 'EXPLODED',
	TOPPLED = 'TOPPLED',
	FLOODED = 'FLOODED',
	SUICIDED = 'SUICIDED',
	LASERED = 'LASERED',
	DETONATED = 'DETONATED',
	SPLATTED = 'SPLATTED',
	POISONED = 'POISONED',
	POISONED_BETA = 'POISONED_BETA',
	POISONED_GAMMA = 'POISONED_GAMMA',
	EXTRA_2 = 'EXTRA_2',
	EXTRA_3 = 'EXTRA_3',
	EXTRA_4 = 'EXTRA_4',
	EXTRA_5 = 'EXTRA_5',
	EXTRA_6 = 'EXTRA_6',
	EXTRA_7 = 'EXTRA_7',
	EXTRA_8 = 'EXTRA_8'
}

export enum Status_t {
	NONE = 'NONE',
	KILLING_SELF = 'KILLING_SELF',
	DISGUISED = 'DISGUISED',
	BOOBY_TRAPPED = 'BOOBY_TRAPPED',
	FAERIE_FIRE = 'FAERIE_FIRE',
	STATUS_RIDER8 = 'STATUS_RIDER8',
	STATUS_RIDER7 = 'STATUS_RIDER7',
	STATUS_RIDER6 = 'STATUS_RIDER6',
	STATUS_RIDER5 = 'STATUS_RIDER5',
	STATUS_RIDER4 = 'STATUS_RIDER4',
	STATUS_RIDER3 = 'STATUS_RIDER3',
	STATUS_RIDER2 = 'STATUS_RIDER2',
	STATUS_RIDER1 = 'STATUS_RIDER1',
	DECK_HEIGHT_OFFSET = 'DECK_HEIGHT_OFFSET',
	IGNORING_STEALTH = 'IGNORING_STEALTH',
	USING_ABILITY = 'USING_ABILITY',
	RECONSTRUCTING = 'RECONSTRUCTING',
	UNDERGOING_REPAIR = 'UNDERGOING_REPAIR',
	SOLD = 'SOLD',
	TOPPLED = 'TOPPLED',
	DETECTED = 'DETECTED',
	STEALTHED = 'STEALTHED',
	IS_AIMING_WEAPON = 'IS_AIMING_WEAPON',
	IS_BRAKING = 'IS_BRAKING',
	IS_CARBOMB = 'IS_CARBOMB',
	IS_FIRING_WEAPON = 'IS_FIRING_WEAPON',
	WET = 'WET',
	AFLAME = 'AFLAME',
	HIJACKED = 'HIJACKED',
	REPULSOR = 'REPULSOR',
	PARACHUTING = 'PARACHUTING',
	AIRBORNE_TARGET = 'AIRBORNE_TARGET',
	NO_ATTACK_FROM_AI = 'NO_ATTACK_FROM_AI',
	MASKED = 'MASKED',
	NO_ATTACK = 'NO_ATTACK',
	NO_COLLISIONS = 'NO_COLLISIONS',
	UNSELECTABLE = 'UNSELECTABLE',
	UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
	CAN_ATTACK = 'CAN_ATTACK',
	CAN_STEALTH = 'CAN_STEALTH',
	DESTROYED = 'DESTROYED',
	REASSIGN_PARKING = 'REASSIGN_PARKING',
	DEPLOYED = 'DEPLOYED'
}

export enum TimeStamp_t {
	INITIAL = 'INITIAL',
	MIDPOINT = 'MIDPOINT',
	FINAL = 'FINAL'
}

export enum ChangeType_t {
	PRESERVE_RATIO = 'PRESERVE_RATIO',
	ADD_CURRENT_HEALTH_TOO = 'ADD_CURRENT_HEALTH_TOO',
	SAME_CURRENTHEALTH = 'SAME_CURRENTHEALTH'
}

export enum CreateLocation_t {
	NONE = 'NONE',
	CREATE_AT_EDGE_FARTHEST_FROM_TARGET = 'CREATE_AT_EDGE_FARTHEST_FROM_TARGET',
	CREATE_AT_EDGE_FARTHEST_FROM_SOURCE = 'CREATE_AT_EDGE_FARTHEST_FROM_SOURCE',
	CREATE_ABOVE_LOCATION = 'CREATE_ABOVE_LOCATION',
	USE_OWNER_OBJECT = 'USE_OWNER_OBJECT',
	CREATE_AT_LOCATION = 'CREATE_AT_LOCATION',
	CREATE_AT_EDGE_NEAR_TARGET = 'CREATE_AT_EDGE_NEAR_TARGET',
	CREATE_AT_EDGE_NEAR_SOURCE = 'CREATE_AT_EDGE_NEAR_SOURCE',
	CREATE_OBJECT = 'CREATE_OBJECT'
}

export enum EditorSorting_t {
	NONE = 'NONE',
	STRUCTURE = 'STRUCTURE',
	VEHICLE = 'VEHICLE',
	INFANTRY = 'INFANTRY',
	SHRUBBERY = 'SHRUBBERY',
	MISC_MAN_MADE = 'MISC_MAN_MADE',
	MISC_NATURAL = 'MISC_NATURAL',
	DEBRIS = 'DEBRIS',
	SYSTEM = 'SYSTEM',
	AUDIO = 'AUDIO',
	TEST = 'TEST',
	FOR_REVIEW = 'FOR_REVIEW',
	ROAD = 'ROAD',
	WAYPOINT = 'WAYPOINT'
}

export enum LOD_t {
	LOW = 'LOW',
	MEDIUM = 'MEDIUM',
	HIGH = 'HIGH'
}

export enum ConditionStateFlags_t {
	NONE = 'NONE',
	DISABLE_ANIMATION = 'DISABLE_ANIMATION',
	START_FRAME_FIRST = 'START_FRAME_FIRST',
	START_FRAME_LAST = 'START_FRAME_LAST',
	ADJUST_HEIGHT_BY_CONSTRUCTION_PERCENT = 'ADJUST_HEIGHT_BY_CONSTRUCTION_PERCENT'
}

export enum WeaponSlot_t {
	PRIMARY = 'PRIMARY',
	SECONDARY = 'SECONDARY',
	TERTIARY = 'TERTIARY'
}

export enum WeaponSetCondition_t {
	NONE = 'NONE',
	PLAYER_UPGRADE = 'PLAYER_UPGRADE',
	WEAPON_RIDER2 = 'WEAPON_RIDER2',
	WEAPON_RIDER3 = 'WEAPON_RIDER3',
	WEAPON_RIDER4 = 'WEAPON_RIDER4',
	WEAPON_RIDER5 = 'WEAPON_RIDER5',
	WEAPON_RIDER6 = 'WEAPON_RIDER6',
	WEAPON_RIDER7 = 'WEAPON_RIDER7',
	WEAPON_RIDER8 = 'WEAPON_RIDER8'
}

export enum AutoAcquireEnemiesWhenIdle_t {
	YES = 'YES',
	NO = 'NO',
	NOTWHILEATTACKING = 'NOTWHILEATTACKING',
	ATTACK_BUILDINGS = 'ATTACK_BUILDINGS',
	ATTACK_UNITS = 'STEALTH'
}

export enum ArmorSetProperty_t {
	CONDITIONS = 'CONDITIONS',
	ARMOR = 'ARMOR',
	DAMAGE_FX = 'DAMAGE_FX'
}

export enum kindOfs_t {
	NONE = 'NONE',
	ALL = 'ALL',
	UNIT = 'UNIT',
	STRUCTURE = 'STRUCTURE',
	SPECIALIGNORE_DOCKING_BONES = 'SPECIALIGNORE_DOCKING_BONES',
	IGNORES_SELECT_ALL = 'IGNORES_SELECT_ALL',
	IGNORED_IN_GUI = 'IGNORED_IN_GUI',
	CONSERVATIVE_BUILDING = 'CONSERVATIVE_BUILDING',
	DEMOTRAP = 'DEMOTRAP',
	EMP_HARDENED = 'EMP_HARDENED',
	TECH_BASE_DEFENSE = 'TECH_BASE_DEFENSE',
	CANNOT_RETALIATE = 'CANNOT_RETALIATE',
	REJECT_UNMANNED = 'REJECT_UNMANNED',
	AIRCRAFT_CARRIER = 'AIRCRAFT_CARRIER',
	OPTIMIZED_TREE = 'OPTIMIZED_TREE',
	PROP = 'PROP',
	BLAST_CRATER = 'BLAST_CRATER',
	BOOBY_TRAP = 'BOOBY_TRAP',
	REVEALS_ENEMY_PATHS = 'REVEALS_ENEMY_PATHS',
	MONEY_HACKER = 'MONEY_HACKER',
	CLIFF_JUMPER = 'CLIFF_JUMPER',
	DONT_AUTO_CRUSH_INFANTRY = 'DONT_AUTO_CRUSH_INFANTRY',
	HERO = 'HERO',
	INERT = 'INERT',
	DISGUISER = 'DISGUISER',
	REVEAL_TO_ALL = 'REVEAL_TO_ALL',
	SUPPLY_SOURCE = 'SUPPLY_SOURCE',
	CANNOT_BUILD_NEAR_SUPPLIES = 'CANNOT_BUILD_NEAR_SUPPLIES',
	SPAWNS_ARE_THE_WEAPONS = 'SPAWNS_ARE_THE_WEAPONS',
	SHOW_PORTRAIT_WHEN_CONTROLLED = 'SHOW_PORTRAIT_WHEN_CONTROLLED',
	HULK = 'HULK',
	IMMUNE_TO_CAPTURE = 'IMMUNE_TO_CAPTURE',
	BOAT = 'BOAT',
	GARRISONABLE_UNTIL_DESTROYED = 'GARRISONABLE_UNTIL_DESTROYED',
	PARACHUTE = 'PARACHUTE',
	PARACHUTABLE = 'PARACHUTABLE',
	SUPPLY_SOURCE_ON_PREVIEW = 'SUPPLY_SOURCE_ON_PREVIEW',
	CLICK_THROUGH = 'CLICK_THROUGH',
	BALLISTIC_MISSILE = 'BALLISTIC_MISSILE',
	DRONE = 'DRONE',
	PRODUCED_AT_HELIPAD = 'PRODUCED_AT_HELIPAD',
	POWERED = 'POWERED',
	TECH_BUILDING = 'TECH_BUILDING',
	AUTO_RALLYPOINT = 'AUTO_RALLYPOINT',
	FORCEATTACKABLE = 'FORCEATTACKABLE',
	LOW_OVERLAPPABLE = 'LOW_OVERLAPPABLE',
	AIRCRAFT_PATH_AROUND = 'AIRCRAFT_PATH_AROUND',
	DEFENSIVE_WALL = 'DEFENSIVE_WALL',
	WALK_ON_TOP_OF_WALL = 'WALK_ON_TOP_OF_WALL',
	ATTACK_NEEDS_LINE_OF_SIGHT = 'ATTACK_NEEDS_LINE_OF_SIGHT',
	ALWAYS_SELECTABLE = 'ALWAYS_SELECTABLE',
	PORTABLE_STRUCTURE = 'PORTABLE_STRUCTURE',
	CLEANUP_HAZARD = 'CLEANUP_HAZARD',
	MINE = 'MINE',
	UNATTACKABLE = 'UNATTACKABLE',
	ALWAYS_VISIBLE = 'ALWAYS_VISIBLE',
	SMALL_MISSILE = 'SMALL_MISSILE',
	CLEARED_BY_BUILD = 'CLEARED_BY_BUILD',
	CAPTURABLE = 'CAPTURABLE',
	CRATE = 'CRATE',
	MOB_NEXUS = 'MOB_NEXUS',
	SCORE_DESTROY = 'SCORE_DESTROY',
	SCORE_CREATE = 'SCORE_CREATE',
	SCORE = 'SCORE',
	REBUILD_HOLE = 'REBUILD_HOLE',
	MP_COUNT_FOR_VICTORY = 'MP_COUNT_FOR_VICTORY',
	DRAWABLE_ONLY = 'DRAWABLE_ONLY',
	CASH_GENERATOR = 'CASH_GENERATOR',
	STEALTH_GARRISON = 'STEALTH_GARRISON',
	HEAL_PAD = 'HEAL_PAD',
	REPAIR_PAD = 'REPAIR_PAD',
	WAVE_EFFECT = 'WAVE_EFFECT',
	WAVEGUIDE = 'WAVEGUIDE',
	NO_GARRISON = 'NO_GARRISON',
	NO_COLLIDE = 'NO_COLLIDE',
	NO_HEAL_ICON = 'NO_HEAL_ICON',
	NO_SELECT = 'NO_SELECT',
	PRELOAD = 'PRELOAD',
	PROJECTILE = 'PROJECTILE',
	BRIDGE_TOWER = 'BRIDGE_TOWER',
	LANDMARK_BRIDGE = 'LANDMARK_BRIDGE',
	BRIDGE = 'BRIDGE',
	TRANSPORT = 'TRANSPORT',
	WEAPON_SALVAGER = 'WEAPON_SALVAGER',
	ARMOR_SALVAGER = 'ARMOR_SALVAGER',
	SALVAGER = 'SALVAGER',
	LINEBUILD = 'LINEBUILD',
	COMMANDCENTER = 'COMMANDCENTER',
	HARVESTER = 'HARVESTER',
	DOZER = 'DOZER',
	HUGE_VEHICLE = 'HUGE_VEHICLE',
	AIRCRAFT = 'AIRCRAFT',
	VEHICLE = 'VEHICLE',
	INFANTRY = 'INFANTRY',
	SHRUBBERY = 'SHRUBBERY',
	STICK_TO_TERRAIN_SLOPE = 'STICK_TO_TERRAIN_SLOPE',
	IMMOBILE = 'IMMOBILE',
	SELECTABLE = 'SELECTABLE',
	OBSTACLE = 'OBSTACLE',
	FS_STRATEGY_CENTER = 'FS_STRATEGY_CENTER',
	FS_SUPPLY_CENTER = 'FS_SUPPLY_CENTER',
	FS_BLACK_MARKET = 'FS_BLACK_MARKET',
	FS_SUPERWEAPON = 'FS_SUPERWEAPON',
	FS_SUPPLY_DROPZONE = 'FS_SUPPLY_DROPZONE',
	FS_AIRFIELD = 'FS_AIRFIELD',
	FS_WARFACTORY = 'FS_WARFACTORY',
	FS_BARRACKS = 'FS_BARRACKS',
	FS_ADVANCED_TECH = 'FS_ADVANCED_TECH',
	FS_TECHNOLOGY = 'FS_TECHNOLOGY',
	FS_BASE_DEFENSE = 'FS_BASE_DEFENSE',
	FS_FACTORY = 'FS_FACTORY',
	FS_POWER = 'FS_POWER',
	FS_INTERNET_CENTER = 'FS_INTERNET_CENTER',
	FS_FAKE = 'FS_FAKE',
	CAN_BE_REPULSED = 'CAN_BE_REPULSED',
	CAN_RAPPEL = 'CAN_RAPPEL',
	CAN_ATTACK = 'CAN_ATTACK',
	CAN_CAST_REFLECTIONS = 'CAN_CAST_REFLECTIONS',
	CAN_SEE_THROUGH_STRUCTURE = 'CAN_SEE_THROUGH_STRUCTURE'
}

export enum Locomotor_types_t {
	SET_NORMAL = 'SET_NORMAL',
	SET_PANIC = 'SET_PANIC',
	SET_NORMAL_UPGRADED = 'SET_NORMAL_UPGRADED',
	SET_SUPERSONIC = 'SET_SUPERSONIC',
	SET_SLUGGISH = 'SET_SLUGGISH',
	SET_TAXIING = 'SET_TAXIING',
	SET_FREEFALL = 'SET_FREEFALL',
	SET_WANDER = 'SET_WANDER'
}

export enum VeterancyTypes_t {
	NORMAL = 'NORMAL',
	VETERAN = 'VETERAN',
	ELITE = 'ELITE',
	HERO = 'HEROIC'
}

