

	
export const allowedObjectProperties: string[] = [
	"Buildable",
	"Scale",
	"RadarPriority",
	"KindOf",
	"SelectPortrait",
	"ButtonImage",
	"UpgradeCameo1",
	"UpgradeCameo2",
	"UpgradeCameo3",
	"UpgradeCameo4",
	"UpgradeCameo5",
	"DisplayName",
	"Side",
	"EditorSorting",
	"TransportSlotCount",
	"PlacementViewAngle",
	"EnergyProduction",
	"EnergyBonus",
	"BuildCost",
	"BuildTime",
	"VisionRange",
	"ShroudClearingRange",
	"ShroudRevealToAllRange",
	"MaxSimultaneousOfType",
	"MaxSimultaneousLinkKey",
	"RefundValue",
	"CrusherLevel",
	"CrushableLevel",
	"ExperienceValue",
	"ExperienceRequired",
	"IsTrainable",
	"CommandSet",
	"VoiceSelect",
	"VoiceGroupSelect",
	"VoiceMove",
	"VoiceEnter",
	"VoiceGuard",
	"VoiceAttack",
	"VoiceAttackAir",
	"VoiceTaskComplete",
	"VoiceFear",
	"VoiceGarrison",
	"SoundStealthOn",
	"SoundStealthOff",
	"SoundMoveStart",
	"SoundMoveStartDamaged",
	"SoundOnDamaged",
	"SoundOnReallyDamaged",
	"SoundAmbientDamaged",
	"SoundAmbientReallyDamaged",
	"SoundEnter",
	"SoundExit",
	"SoundAmbient",
	"SoundAmbientRubble",
	"Locomotor",
	"Geometry",
	"GeometryMajorRadius",
	"GeometryMinorRadius",
	"GeometryHeight",
	"GeometryIsSmall",
	"Shadow",
	"FenceWidth",
	"FenceXOffset",
	"ShadowSizeX",
	"BuildCompletion",
	"FactoryExitWidth",
	"ShadowTexture",
	"FactoryExtraBibWidth",
	"ShadowSizeY"
];

export const allowedAddModuleProperties: string[] = [
	"Locomotor",
];


export const allowedLocomotorProperties: string[] = [
	"SET_NORMAL",
	"SET_PANIC",
	"SET_NORMAL_UPGRADED",
	"SET_SUPERSONIC",
	"SET_SLUGGISH",
	"SET_TAXIING",
	"SET_FREEFALL",
	"SET_WANDER"
];

export const kindOfs: string[] = [
    "UNIT",
    "STRUCTURE",
    "SPECIALIGNORE_DOCKING_BONES",
    "IGNORES_SELECT_ALL",
    "IGNORED_IN_GUI",
    "CONSERVATIVE_BUILDING",
    "DEMOTRAP",
    "EMP_HARDENED",
    "TECH_BASE_DEFENSE",
    "CANNOT_RETALIATE",
    "REJECT_UNMANNED",
    "AIRCRAFT_CARRIER",
    "OPTIMIZED_TREE",
    "PROP",
    "BLAST_CRATER",
    "BOOBY_TRAP",
    "REVEALS_ENEMY_PATHS",
    "MONEY_HACKER",
    "CLIFF_JUMPER",
    "DONT_AUTO_CRUSH_INFANTRY",
    "HERO",
    "INERT",
    "DISGUISER",
    "REVEAL_TO_ALL",
    "SUPPLY_SOURCE",
    "CANNOT_BUILD_NEAR_SUPPLIES",
    "SPAWNS_ARE_THE_WEAPONS",
    "SHOW_PORTRAIT_WHEN_CONTROLLED",
    "HULK",
    "IMMUNE_TO_CAPTURE",
    "BOAT",
    "GARRISONABLE_UNTIL_DESTROYED",
    "PARACHUTE",
    "PARACHUTABLE",
    "SUPPLY_SOURCE_ON_PREVIEW",
    "CLICK_THROUGH",
    "BALLISTIC_MISSILE",
    "DRONE",
    "PRODUCED_AT_HELIPAD",
    "POWERED",
    "TECH_BUILDING",
    "AUTO_RALLYPOINT",
    "FORCEATTACKABLE",
    "LOW_OVERLAPPABLE",
    "AIRCRAFT_PATH_AROUND",
    "DEFENSIVE_WALL",
    "WALK_ON_TOP_OF_WALL",
    "ATTACK_NEEDS_LINE_OF_SIGHT",
    "ALWAYS_SELECTABLE",
    "PORTABLE_STRUCTURE",
    "CLEANUP_HAZARD",
    "MINE",
    "UNATTACKABLE",
    "ALWAYS_VISIBLE",
    "SMALL_MISSILE",
    "CLEARED_BY_BUILD",
    "CAPTURABLE",
    "CRATE",
    "MOB_NEXUS",
    "SCORE_DESTROY",
    "SCORE_CREATE",
    "SCORE",
    "REBUILD_HOLE",
    "MP_COUNT_FOR_VICTORY",
    "DRAWABLE_ONLY",
    "CASH_GENERATOR",
    "STEALTH_GARRISON",
    "HEAL_PAD",
    "REPAIR_PAD",
    "WAVE_EFFECT",
    "WAVEGUIDE",
    "NO_GARRISON",
    "NO_COLLIDE",
    "NO_HEAL_ICON",
    "NO_SELECT",
    "PRELOAD",
    "PROJECTILE",
    "BRIDGE_TOWER",
    "LANDMARK_BRIDGE",
    "BRIDGE",
    "TRANSPORT",
    "WEAPON_SALVAGER",
    "ARMOR_SALVAGER",
    "SALVAGER",
    "LINEBUILD",
    "COMMANDCENTER",
    "HARVESTER",
    "DOZER",
    "HUGE_VEHICLE",
    "AIRCRAFT",
    "VEHICLE",
    "INFANTRY",
    "STRUCTURE",
    "SHRUBBERY",
    "STICK_TO_TERRAIN_SLOPE",
    "IMMOBILE",
    "SELECTABLE",
    "OBSTACLE",
    "FS_STRATEGY_CENTER",
    "FS_SUPPLY_CENTER",
    "FS_BLACK_MARKET",
    "FS_SUPERWEAPON",
    "FS_SUPPLY_DROPZONE",
    "FS_AIRFIELD",
    "FS_WARFACTORY",
    "FS_BARRACKS",
    "FS_ADVANCED_TECH",
    "FS_TECHNOLOGY",
    "FS_BASE_DEFENSE",
    "FS_FACTORY",
    "FS_POWER",
    "FS_INTERNET_CENTER",
    "FS_FAKE",
    "CAN_BE_REPULSED",
    "CAN_RAPPEL",
    "CAN_ATTACK",
    "CAN_CAST_REFLECTIONS",
    "CAN_SEE_THROUGH_STRUCTURE"
];

export const allowedModelDrawsString: string[] = [
	"w3ddebrisdraw",
    "w3ddefaultdraw",
    "w3ddependencymodeldraw",
    "w3dmodeldraw",
    "w3doverlordtankdraw",
    "w3doverlordaircraftdraw",
    "w3doverlordtruckdraw",
    "w3dlaserdraw",
	"w3dpolicecardraw",
    "w3dtreedraw",
    "w3dpropdraw",
    "w3dprojectilestreamdraw",
    "w3dropedraw",
    "w3dsciencemodeldraw",
    "w3dsupplydraw",
    "w3dtankdraw",
    "w3dtanktruckdraw",
    "w3dtracerdraw",
    "w3dtruckdraw"
]

export enum allowedModelDraws {
    W3DDEBRISDRAW = "w3ddebrisdraw",
    W3DDEFAULTDRAW = "w3ddefaultdraw",
    W3DDEPENDENCYMODELDRAW = "w3ddependencymodeldraw",
    W3DMODELDRAW = "w3dmodeldraw",
    W3DOVERLORDTANKDRAW = "w3doverlordtankdraw",
    W3DOVERLORDAIRCRAFTDRAW = "w3doverlordaircraftdraw",
    W3DOVERLORDTRUCKDRAW = "w3doverlordtruckdraw",
    W3DLASERDRAW = "w3dlaserdraw",
    W3DPOLICECARDRAW = "w3dpolicecardraw",
    W3DTREEDRAW = "w3dtreedraw",
    W3DPROPDRAW = "w3dpropdraw",
    W3DPROJECTILESTREAMDRAW = "w3dprojectilestreamdraw",
    W3DROPEDRAW = "w3dropedraw",
    W3DSCIENCEMODELDRAW = "w3dsciencemodeldraw",
    W3DSUPPLYDRAW = "w3dsupplydraw",
    W3DTANKDRAW = "w3dtankdraw",
    W3DTANKTRUCKDRAW = "w3dtanktruckdraw",
    W3DTRACERDRAW = "w3dtracerdraw",
    W3DTRUCKDRAW = "w3dtruckdraw"
}

export const allowedSingleModelDrawProperties: string[] = [
	"TrackMarks",
	"Dust",
	"DirtSpray",
	"PowerslideSpray",
	"AliasConditionState",
	"TransitionState",
	"IgnoreConditionStates",
	"AnimationRequirePower",
	"MinLODRequired",
	"OkToChangeModelColor",
	"ReceivesDynamicLights",
	"ParticlesAttachedToAnimatedBones",
	"ProjectileBoneFeedbackEnabledSlots",
	"AttachToBoneInAnotherModule",
	"InitialRecoilSpeed",
	"MaxRecoilDistance",
	"RecoilSettleSpeed",
	"RecoilDamping",
	"AnimationsRequirePower"
];

export const allowedMultiModelDrawProperties: string[] = [
	"ExtraPublicBone"
];

export const allowedTankDrawProperties: string[] = [
	"TreadDriveSpeedFraction",
	"TreadPivotSpeedFraction",
	"TreadAnimationRate",
	"TreadDebrisLeft",
	"TreadDebrisRight"
];

export const allowedTruckDrawProperties: string[] = [
	"RotationDamping",
	"TrailerRotationMultiplier",
	"TrailerBone",
	"CabRotationMultiplier",
	"CabBone",
	"PowerslideRotationAddition",
	"TireRotationMultiplier",
	"MidRightMidTireBone",
	"MidLeftMidTireBone",
	"MidRightRearTireBone",
	"MidLeftRearTireBone",
	"MidRightFrontTireBone",
	"MidLeftFrontTireBone",
	"RightRearTireBone",
	"LeftRearTireBone",
	"RightFrontTireBone",
	"LeftFrontTireBone",
	"PowerslideSpray",
	"DirtSpray",
	"Dust",
	"TrackMarks",
	"Dust",
	"DirtSpray",
	"PowerslideSpray",
	"AliasConditionState",
	"TransitionState",
	"IgnoreConditionStates",
	"AnimationRequirePower",
	"MinLODRequired",
	"OkToChangeModelColor",
	"ReceivesDynamicLights",
	"ParticlesAttachedToAnimatedBones",
	"ProjectileBoneFeedbackEnabledSlots",
	"AttachToBoneInAnotherModule",
	"InitialRecoilSpeed",
	"MaxRecoilDistance",
	"RecoilSettleSpeed",
	"RecoilDamping",
	"AnimationsRequirePower"
];

export const allowedTankTruckDrawProperties = [
	"RotationDamping",
	"TrailerRotationMultiplier",
	"TrailerBone",
	"CabRotationMultiplier",
	"CabBone",
	"PowerslideRotationAddition",
	"TireRotationMultiplier",
	"MidRightMidTireBone",
	"MidLeftMidTireBone",
	"MidRightRearTireBone",
	"MidLeftRearTireBone",
	"MidRightFrontTireBone",
	"MidLeftFrontTireBone",
	"RightRearTireBone",
	"LeftRearTireBone",
	"RightFrontTireBone",
	"LeftFrontTireBone",
	"PowerslideSpray",
	"DirtSpray",
	"Dust",
	"TrackMarks",
	"Dust",
	"DirtSpray",
	"PowerslideSpray",
	"AliasConditionState",
	"TransitionState",
	"IgnoreConditionStates",
	"AnimationRequirePower",
	"MinLODRequired",
	"OkToChangeModelColor",
	"ReceivesDynamicLights",
	"ParticlesAttachedToAnimatedBones",
	"ProjectileBoneFeedbackEnabledSlots",
	"AttachToBoneInAnotherModule",
	"InitialRecoilSpeed",
	"MaxRecoilDistance",
	"RecoilSettleSpeed",
	"RecoilDamping",
	"AnimationsRequirePower",
	"TreadDriveSpeedFraction",
	"TreadPivotSpeedFraction",
	"TreadAnimationRate",
	"TreadDebrisLeft",
	"TreadDebrisRight"
];

export const allowedDependencyDrawProperties: string[] = [
	"AttachToBoneInContainer"
];

export const allowedScienceDrawProperties: string[] = [
	"InitialRecoilSpeed",
    "MaxRecoilDistance",
    "RecoilDamping",
    "RecoilSettleSpeed",
    "OkToChangeModelColor",
    "AnimationsRequirePower",
    "ParticlesAttachedToAnimatedBones",
    "MinLODRequired",
    "ProjectileBoneFeedbackEnabledSlots",
	"TrackMarks",
    "ExtraPublicBone",
    "AttachToBoneInAnotherModule",
    "IgnoreConditionStates",
    "ReceivesDynamicLights",
    "RequiredScience"
]

export const allowedSupplyDrawProperties: string[] = [
	"InitialRecoilSpeed",
    "MaxRecoilDistance",
    "RecoilDamping",
    "RecoilSettleSpeed",
    "OkToChangeModelColor",
    "AnimationsRequirePower",
    "ParticlesAttachedToAnimatedBones",
    "MinLODRequired",
    "ProjectileBoneFeedbackEnabledSlots",
	"TrackMarks",
    "ExtraPublicBone",
    "AttachToBoneInAnotherModule",
    "IgnoreConditionStates",
    "ReceivesDynamicLights",
    "SupplyBonePrefix"
]

export const allowedTreeDrawProperties: string[] = [
	"ModelName",
	"TextureName",
	"MinimumToppleSpeed",
	"DoTopple",
	"DoShadow",
	"ToppleFX",
	"BounceFX",
	"KillWhenFinishedToppling",
	"SinkDistance",
	"SinkTime",
	"DarkeningFactor",
	"MoveInwardTime",
	"MoveOutwardTime",
	"MoveOutwardDistanceFactor"
];

export const allowedProjectileStreamDrawProperties: string[] = [
	"Texture",
	"Width",
	"TileFactor",
	"ScrollRate",
	"MaxSegments"
];

export const allowedLaserDrawProperties: string[] = [
	"Texture",
	"NumBeams",
	"InnerBeamWidth",
	"OuterBeamWidth",
	"InnerColor",
	"OuterColor",
	"MaxIntensityLifetime",
	"FadeLifetime",
	"Tile",
	"Segments",
	"SegmentOverlapRatio",
	"ArcHeight",
	"TilingScalar",
	"ScrollRate"
];

export const allowedSingleConditionProperties: string[] = [
	"Model",
	"WeaponHideShowBone",
	"AnimationSpeedFactorRange",
	"AnimationMode",
	"TransitionKey",
	"Flags",
	"WaitForStateToFinishIfPossible",
	"Turret",
	"TurretArtAngle",
	"TurretPitch",
	"TurretArtPitch",
	"AltTurret",
	"AltTurretArtAngle",
	"AltTurretPitch",
	"AltTurretArtPitch",
	"ShowSubObject",
	"HideSubObject",
];

export const allowedMultiConditionProperties: string[] = [
	"WeaponRecoilBone",
	"WeaponFireFXBone",
	"WeaponMuzzleFlash",
	"WeaponLaunchBone",
	"Animation",
	"IdleAnimation",
	"ParticleSysBone"
];

export let allowedConditionStates: string[] = [
	"NONE",
	"USER_1",
	"USER_2",
	"JAMMED",
	"ATTACKING",
	"WEAPONSET_CRATEUPGRADE_ONE",
	"WEAPONSET_CRATEUPGRADE_TWO",
	"ARMORSET_CRATEUPGRADE_TWO",
	"ARMORSET_CRATEUPGRADE_ONE",
	"PREORDER",
	"STUNNED",
	"STUNNED_FLAILING",
	"EXPLODED_BOUNCING",
	"EXPLODED_FLAILING",
	"CAPTURED",
	"RAISING_FLAG",
	"CONTINUOUS_FIRE_SLOW",
	"CONTINUOUS_FIRE_FAST",
	"CONTINUOUS_FIRE_MEAN",
	"SPECIAL_CHEERING",
	"ARMED",
	"RAPELLING",
	"PARACHUTING",
	"CLIMBING",
	"SPLATTED",
	"BURNED",
	"AFLAME",
	"SMOLDERING",
	"POWER_PLANT_UPGRADING",
	"POWER_PLANT_UPGRADED",
	"OVER_WATER",
	"MOVING",
	"DEPLOYED",
	"UNPACKING",
	"PACKING",
	"JETEXHAUST",
	"JETAFTERBURNER",
	"LOADED",
	"CARRYING",
	"DOCKING_ENDING",
	"DOCKING_ACTIVE",
	"DOCKING_BEGINNING",
	"DOCKING",
	"PANICKING",
	"RADAR_UPGRADED",
	"RADAR_EXTENDED",
	"CONSTRUCTION_COMPLETE",
	"ACTIVELY_CONSTRUCTING",
	"ACTIVELY_BEING_CONSTRUCTED",
	"PARTIALLY_CONSTRUCTED",
	"AWAITING_CONSTRUCTION",
	"DYING",
	"PRONE",
	"FREEFALL",
	"POST_COLLAPSE",
	"TOPPLED",
	"TURRET_ROTATE",
	"RELOADING_A",
	"BETWEEN_FIRING_SHOTS_A",
	"FIRING_A",
	"PREATTACK_A",
	"USING_WEAPON_A",
	"RELOADING_B",
	"BETWEEN_FIRING_SHOTS_B",
	"FIRING_B",
	"PREATTACK_B",
	"USING_WEAPON_B",
	"RELOADING_C",
	"BETWEEN_FIRING_SHOTS_C",
	"FIRING_C",
	"PREATTACK_C",
	"USING_WEAPON_C",
	"DOOR_4_WAITING_TO_CLOSE",
	"DOOR_4_WAITING_OPEN",
	"DOOR_4_CLOSING",
	"DOOR_4_OPENING",
	"DOOR_3_WAITING_TO_CLOSE",
	"DOOR_3_WAITING_OPEN",
	"DOOR_3_CLOSING",
	"DOOR_3_OPENING",
	"DOOR_2_WAITING_TO_CLOSE",
	"DOOR_2_WAITING_OPEN",
	"DOOR_2_CLOSING",
	"DOOR_2_OPENING",
	"DOOR_1_WAITING_TO_CLOSE",
	"DOOR_1_WAITING_OPEN",
	"DOOR_1_CLOSING",
	"DOOR_1_OPENING",
	"WEAPONSET_PLAYER_UPGRADE",
	"WEAPONSET_HERO",
	"WEAPONSET_ELITE",
	"WEAPONSET_VETERAN",
	"ENEMYNEAR",
	"REALLYDAMAGED",
	"RUBBLE",
	"DAMAGED",
	"SNOW",
	"SOLD",
	"DISGUISED",
	"NIGHT",
	"RAPPELLING",
	"SPECIAL_DAMAGED",
	"BACKCRUSHED",
	"FRONTCRUSHED",
	"SECOND_LIFE",
	"RIDER1",
	"RIDER2",
	"RIDER3",
	"RIDER4",
	"RIDER5",
	"RIDER6",
	"RIDER7",
	"RIDER8",
	"PRISTINE",
	"RIGHT_TO_CENTER",
	"CENTER_TO_RIGHT",
	"LEFT_TO_CENTER",
	"CENTER_TO_LEFT",
	"DOWN_DEFAULT",
	"AWAITING_CONSTRUCTION",
	"PARTIALLY_CONSTRUCTED",
	"ACTIVELY_BEING_CONSTRUCTED",
	"UP_DAY",
	"UP_NIGHT",
	"UP_SNOW",
	"UP_SNOWNIGHT",
	"RADAR_EXTENDING",
	"GARRISONED"
];