export enum DrawModule_t {
	W3DDEBRISDRAW = "W3DDebrisDraw",
	W3DDEFAULT = "W3DDefaultDraw",
	W3DDEPENDENCYMODELDRAW = "W3DDependencyModelDraw",
	W3DMODELDRAW = "W3DModelDraw",
	W3DOverlordTANKDRAW = "W3DOverlordTankDraw",
	W3DOverlordAIRCRAFTDRAW = "W3DOverlordAircraftDraw",
	W3DOverlordTRUCKDRAW = "W3DOverlordTruckDraw",
	W3DLLASERDRAW = "W3DLaserDraw",
	W3DPOLICECARDRAW = "W3DPoliceCarDraw",
	W3DTREEDRAW = "W3DTreeDraw",
	W3DPROPDRAW = "W3DPropDraw",
	W3DPROJECTILESTREAMDRAW = "W3DProjectileStreamDraw",
	W3DDROPEDRAW = "W3DDropedraw",
	W3DSCIENCEMODELDRAW = "W3DScienceModelDraw",
	W3DSUPPLYDRAW = "W3DSupplyDraw",
	W3DTANKDRAW = "W3DTankDraw",
	W3DTANKTRUCKDRAW = "W3DTankTruckDraw",
	W3DTRACERDRAW = "W3DTracerDraw",
	W3DTRUCKDRAW = "W3DTruckDraw"
}